name: OpenVPN
description: Virtual private network
version: 1.0.6
slug: openvpn
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
host_network: true
privileged:
  - NET_ADMIN
  - SYS_RAWIO
